### ISSUE TITLE
Vendor dependencies

### ISSUE THREAD

**Issue by cswank** [gchaincl/httplab#1]
This is a cool project and I'd like to be able to use it, but I have another version of gocui installed that doesn't jive with this project.  When I try to build:  

go get github.com/gchaincl/httplab
# github.com/gchaincl/httplab
../../gchaincl/httplab/main.go:36: undefined: gocui.Output256
../../gchaincl/httplab/main.go:36: too many arguments in call to gocui.NewGui
../../gchaincl/httplab/main.go:36: assignment count mismatch: 2 = 1
../../gchaincl/httplab/ui.go:106: g.Highlight undefined (type *gocui.Gui has no field or method Highlight)
../../gchaincl/httplab/ui.go:127: v.Editor undefined (type *gocui.View has no field or method Editor)
../../gchaincl/httplab/ui.go:154: v.Editor undefined (type *gocui.View has no field or method Editor)
../../gchaincl/httplab/ui.go:165: v.Editor undefined (type *gocui.View has no field or method Editor)
../../gchaincl/httplab/ui.go:174: v.Editor undefined (type *gocui.View has no field or method Editor)
../../gchaincl/httplab/ui.go:187: v.Editor undefined (type *gocui.View has no field or method Editor)
../../gchaincl/httplab/ui.go:195: assignment count mismatch: 2 = 1
../../gchaincl/httplab/ui.go:195: too many errors

I'd be able to try it out easily if you could vendor gocui and friends.

**Comment by gchaincl** [comment]
That would make a lot of sense, thanks for reporting the issue.
I'll fix it ASAP.

**Comment by gchaincl** [comment]
@cswank can you confirm if now works for you?

**Comment by cswank** [comment]
Confirmed, it's working now!  Thanks.
