### ISSUE TITLE
[Archlinux] default 644 does not contain executable bit

### ISSUE THREAD

**Issue by juliosueiras** [gchaincl/httplab#11]
**Issue:**
Due to the 644 mode in PKGBUILD, the httplab will install as a ordinary file, instead of a executable

**Fix:**
change 644 to 755

**Comment by gchaincl** [comment]
Thanks, it's already fixed here: https://github.com/gchaincl/httplab/commit/31517462ca30423a222282f75f2c50bf26115d3a
