### ISSUE TITLE
Support Environment Variables in Body File

### ISSUE THREAD

**Issue by jacksgt** [gchaincl/httplab#18]
As an enhancement of #14, another nice-to-have feature would be the support of environment variables for the string specifying the response file.

This should open up many convenient use cases.

E.g. `~/test.txt` expands to `/home/jack/test.txt`
 
But also: `$HOME`, `$TMP`, `$USER`, `$PATH`, `$LANGUAGE` ...

**Comment by jacksgt** [comment]
Wow, that was quick action! Amazing!

**Comment by gchaincl** [comment]
Cool, thanks for the ideas, I've never though about it.
BTW: I saw you were working on https://github.com/asciimoo/wuzz/issues/72#issuecomment-284073151, it would be awesome to get your help on a debian package for httplab too :)

**Comment by jacksgt** [comment]
@gchaincl I'll look into it, but since your project isn't a dependency mess, it shouldn't be too hard :-)
Although I can't give you an ETA yet.

**Comment by gchaincl** [comment]
Ok, great to hear!, There's no hurries on this.
