### ISSUE TITLE
Execution steps for Windows 7

### ISSUE THREAD

**Issue by d-saravanan** [gchaincl/httplab#21]
Hi,

I have installed go on my Machine and then tried the go get command. The command completed without any response. Kindly let me know how can I run this app in Windows 7. I am new to Go, so detailed instructions or any link will be very helpful for me

Regards
Saravanan

**Comment by gchaincl** [comment]
I've never ran Golang on Windows, but what I'd try is:
* https://nats.io/documentation/tutorials/go-install/ (windows section)
* `go get -v github.com/gchaincl/httplab`
* `httplab` or `cd %GOPATH%; httplab`

**Comment by gchaincl** [comment]
@d-saravanan any luck?

**Comment by d-saravanan** [comment]
I tried this, but my bad, the httplab does not work for me
