### ISSUE TITLE
Form POST hard to view

### ISSUE THREAD

**Issue by swordbeta** [gchaincl/httplab#26]
The body of form POST requests is very hard to read due to there being no word wrapping and home/end buttons not working, see:

![screenshot from 2017-04-20 11-24-26](https://cloud.githubusercontent.com/assets/7511094/25223635/32a8b162-25bc-11e7-9aad-343acbcea2d2.png)

**Comment by gchaincl** [comment]
I'm aware of that, but still not sure how to solve it, enabling word wrapping can lead to confusions as well, any suggestions?

**Comment by gchaincl** [comment]
A work around to that would be to toggle the response builder <kbd>Ctrl+t</kbd>, that should give you a little extra space to read the body

**Comment by swordbeta** [comment]
If you make it clear the body is being wrapped with like a colored dash, then it should be pretty good I think?

Another 'solution' would be if we could save the request body so we can open it in a dedicated editor.

**Comment by gchaincl** [comment]
Saving the request into a file sounds like a great idea, I'll see what I
can get.
