### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by AxelTheGerman** [gchaincl/httplab#3]
Would be super neat if the tool could either pick up the .httplab config file from the current directory or via command line argument (similar to the port configuration).
That would allow to have different saved requests for different projects and also to version control the saved requests.

**Comment by gchaincl** [comment]
Sounds like a great idea!, I'll think about the implementation, thanks!

**Comment by gchaincl** [comment]
Now httplab look for a `.httplab` file on the `pwd`, if not found it falls back to `$HOME/.httplab`. You can also specify a custom file using the `-config` flag.

**Comment by j-manu** [comment]
Can you please provide some example config files? If httplab supports non text responses (images for example) config for that will be great.

This is a great tool. Thank you :)

**Comment by gchaincl** [comment]
@j-manu I'll upload some example, about the non-text responses, it's a wonderful idea, I'm not sure how to display that on the UI yet, any idea?

**Comment by j-manu** [comment]
Full path to file should be sufficient

**Comment by AxelTheGerman** [comment]
not sure about the images (great idea though), but regarding sample config you could just create a couple of responses in the tool and take a look at the `.httplab` file.
The main idea for being able to specify the file location was not to manually write responses in that file, but just to be able to swap it out depending on the context (project or whatever) and version control it
