### ISSUE TITLE
Document the API using Godoc

### ISSUE THREAD

**Issue by gchaincl** [gchaincl/httplab#35]
At some point, HTTPLab should be able to be used as a library, so that you can build your own frontends. To do so, we need to start documenting it properly.

**Comment by homuncculus** [comment]
I'll give it a try

**Comment by gchaincl** [comment]
@homuncculus thanks for your interest in contributing, I think @planchao is already working on it.
I'm trying to avoid duplicated work.

**Comment by gchaincl** [comment]
Closed by #62
