### ISSUE TITLE
"Save response as" not working

### ISSUE THREAD

**Issue by spemberton** [gchaincl/httplab#37]
I tried to do "Save response as", and got the message "open /home/steven/.httplab: permission denied".

I tried making a directory .httplab (complained that it was a directory), and later a text file (complained permission denied).

I tried saving using a relative file name, and a full file name, and nothing was saved.

**Comment by gchaincl** [comment]
@spemberton are you sure `.httplab` hasn't been created before with other permissions?

**Comment by spemberton** [comment]
Absolutely sure.

**Comment by spemberton** [comment]
In another thread, you said "About saving #37 you need to save the request, not the response."
I don't see that option, and I see now you said to use ctrl-f, which is not offered. I'm using Ubuntu snap v0.2.0

**Comment by gchaincl** [comment]
That makes sense, Request Saving it's been implemented in 0.3.0 https://github.com/gchaincl/httplab/blob/master/CHANGELOG.md#v030-dev, not released yet.

Please, try to install HTTPLab using `go get` to try `-dev` features.

**Comment by gchaincl** [comment]
can u `ls -l .httplab` ?

**Comment by spemberton** [comment]
steven@steven-XPS:~$ ls -l .httplab
-rw-rw-r-- 1 steven steven 534 Jun 27 11:02 .httplab
steven@steven-XPS:~$ cat .httplab
{
2	  "Responses": {
3	    "ok": {
4	      "Status": 200,
5	      "Delay": 0,
6	      "Body": "Hello, World",
7	      "Headers": {
8	        "X-Server": "XForms"
9	      }
10	    },
11	    "create": {
12	      "Status": 201,
13	      "Delay": 1000,
14	      "Body": "{\"created\":\"ok\"}",
15	      "Headers": {
16	        "Content-Type": "application/json"
17	      }
18	    },
19	    "notfound": {
20	      "Status": 404,
21	      "Delay": 0,
22	      "Body": "Page Not Found",
23	      "Headers": {
24	      }
25	    }
26	  }
27	}

**Comment by gchaincl** [comment]
so `.httplab` file has been written, can you try to `mv .httplab .httplab.bkp` and try again?
Remember that `Save Response` used to save predefined responses.

**Comment by spemberton** [comment]
I created .httplab to see if that would solve the problem. It didn't. With no .httplab, I get the same result.

**Comment by gchaincl** [comment]
but try to instead of creating it, remove it and let httplab create it for you

**Comment by spemberton** [comment]
I did. It didn't create it.

**Comment by gchaincl** [comment]
what was the error message?

**Comment by spemberton** [comment]
"open /home/steven/.httplab: permission denied". (See first message in this thread)

**Comment by gchaincl** [comment]
ok, but who created the `.httplab` file you showed be above?

**Comment by spemberton** [comment]
Me. I created it to see if it would make a difference. Same result.

**Comment by gchaincl** [comment]
I can't reproduce it, I'm sorry

**Comment by gchaincl** [comment]
It's an OS permission problem, which makes me think it escapes from HTTPLab scope.

**Comment by spemberton** [comment]
I don't understand why you would try to read .httplab when trying to save the responses to a file.

**Comment by gchaincl** [comment]
.httplab file holds a list of predefined responses

**Comment by spemberton** [comment]
I can confirm that this problem is solved in the latest version v0.3.0-dev
