### ISSUE TITLE
Support for HTTPS

### ISSUE THREAD

**Issue by kphatak** [gchaincl/httplab#4]
it would be really helpful for fast development and debugging of an existing API.

**Comment by gchaincl** [comment]
Definitively, should we accept both, http and https at the same time or do it selectively?

**Comment by ip1981** [comment]
If you mean HTTP over TLS, this looks out of scope.

**Comment by ip1981** [comment]
I mean if this tool is about inspecting HTTP, then transport does not matter.

**Comment by SikhNerd** [comment]
Agreed with @ip1981 I'm not seeing how this tool would support https in a meaningful way without a huge increase in scope.

**Comment by gchaincl** [comment]
@kphatak, @ip and @SikhNerd makes me realizes that HTTPS is out of the scope of the project for now.
I've create instructions on how to use a stunnel tu proxy HTTPS traffic here: https://github.com/gchaincl/httplab/tree/master/contrib/stunnel
Hope it works!
