### ISSUE TITLE
Location header not rendered to client

### ISSUE THREAD

**Issue by vjeantet** [gchaincl/httplab#44]
Hello,

 When i set `Location: http://google.fr` in Headers panel, this header never write out to the client.
 the `:` seems to cause the issue, because when i set `Location: http//google.fr' it works

**Comment by vjeantet** [comment]
this helps
```
diff --git a/response.go b/response.go
index 70d3d14..0a6d5dd 100644
--- a/response.go
+++ b/response.go
@@ -96,7 +96,7 @@ func NewResponse(status, headers, body string) (*Response, error) {
                        continue
                }
 
-               kv := strings.Split(line, ":")
+               kv := strings.SplitN(line, ":", 2)
                if len(kv) != 2 {
                        continue
                }
```

**Comment by gchaincl** [comment]
Good catch. it would be great if you could open a PR with that change.

**Comment by gchaincl** [comment]
oh I didn't notice that you already did https://github.com/gchaincl/httplab/pull/45 😆
