### ISSUE TITLE
Display request headers sorted

### ISSUE THREAD

**Issue by gchaincl** [gchaincl/httplab#47]
As request headers are implemented as a map, the order of the keys are not guaranteed.
It would be nice to display all the request header sorted alphabetically, so that is easy to identify changes from one request to the other

**Comment by j-haj** [comment]
It seems this is referring to to the `DumpRequest` function -- is that correct?

**Comment by waleoyediran** [comment]
Yes. that is correct @j-haj 
it dumps the headers in alphabetical order (by keys)

**Comment by j-haj** [comment]
Alright I think I have a patch that should add this. Test appear to be passing, will submit a PR later today.

**Comment by gchaincl** [comment]
Excellent!!

**Comment by gchaincl** [comment]
Closed by #48
