### ISSUE TITLE
Support for short flags

### ISSUE THREAD

**Issue by gchaincl** [gchaincl/httplab#49]
Right now we just support long flag format (ie `-port`, `-config`, etc). It would be nice to provide the short version for: `port`, `config` and `version`.

https://github.com/alecthomas/kingpin looks like a great candidate for this, but any other should be fine.

**Comment by dnguy078** [comment]
@gchaincl https://github.com/gchaincl/httplab/pull/50

**Comment by sponomarev** [comment]
Hey, @gchaincl!

#51 Here is my solution 😄

**Comment by gchaincl** [comment]
Cool, both looks really well, as I don't have a strong opinion on which library to use pflag, o kingpin, I'll add comment to both, the first one in resolve them, gets merged!

**Comment by gchaincl** [comment]
Closed by #50
