### ISSUE TITLE
Add some linting to CI

### ISSUE THREAD

**Issue by gchaincl** [gchaincl/httplab#53]
It would be great to have a linter as part of the CI (travis)

**Comment by niranjan92** [comment]
i can take this up

**Comment by gchaincl** [comment]
cool!!

**Comment by sponomarev** [comment]
@gchaincl Done #55. Should we fail the build in case of any issues?  There's a lot of them atm.

**Comment by srini156** [comment]
@gchaincl - Let me know if you need to clean up the existing lint failures. I would like to help. I would definitely want to enforce build failures in case of lint violations going forward 💯

**Comment by gchaincl** [comment]
@srini156 yes I need help on that too!
