### ISSUE TITLE
Text selecting support using mouse

### ISSUE THREAD

**Issue by gchaincl** [gchaincl/httplab#54]
Unless you're using tmux (or some terminal multiplexer) copying text to the clipboard it's hard, this is mainly because you can't select text using the mouse.
This would be a nice to have feature.

**Comment by dnguy078** [comment]
I can take a stab at this

**Comment by sponomarev** [comment]
Unfortunately, it seems like a limitation of gocui

**Comment by gchaincl** [comment]
@sponomarev does termbox provides that?

**Comment by sponomarev** [comment]
@gchaincl I don't think so. I guess it's a limitation of mouse handling in the terminal. I've checked the most popular terminal product with mouse support - midnight commander. It uses ncurses which is much more advanced than their competitors and even it doesn't support text selection with mouse.

I want to underline that it's just a guess. I'm not an expert in terminal questions.

**Comment by gchaincl** [comment]
Thanks for investigate into it, I'll let this open until someone else confirms

**Comment by avdv** [comment]
Usually, you can select text in terminal apps like midnight Commander while holding the shift key. This works just fine for me with httplab too!

**Comment by gchaincl** [comment]
Oh I didn't knew that. @dnguy078 are u still working on this? Otherwise I'll close it

**Comment by gchaincl** [comment]
Looks like there's nothing we can do to fix it, so I'm closing this
