### ISSUE TITLE
Create a logo

### ISSUE THREAD

**Issue by gchaincl** [gchaincl/httplab#58]
I haven't been able to come up with a good logo.
I'd love to see some proposals, the most 👍 voted will be chosen!

**Comment by harleo** [comment]
@gchaincl 
I'll give it a try

**Comment by gchaincl** [comment]
Great @harleo

**Comment by nightrainlily** [comment]
@gchaincl any idea what you're looking for? just a text logo for httplab?

**Comment by gchaincl** [comment]
@nightrainlily my approach would be text with some "representative typography", also, I wouldn't use a pet (like docker, or linux) but to be honest I don't have any strong opinion and every proposal will be kindly accepted

**Comment by stevenanthonyrevo** [comment]
@gchaincl Are you still in need of help? I'd like to Join in as well.

**Comment by gchaincl** [comment]
@stevenanthonyrevo yes sure, the idea is that people come up with logos, upload them into this issue, and then choose the most voted.

**Comment by vkolova** [comment]
![httplab logo by vkolova](https://raw.githubusercontent.com/vkolova/httplab/58caefc183c5766474464e8d30a97cd4dd8b16a0/images/httplab_logo.png) Also featured in my PR.

**Comment by gchaincl** [comment]
Great start!, I like it. Let's wait for others proposals!

**Comment by harleo** [comment]
Threw something together.
I'll do a PR when my logo is chosen.

![httplab_artboard_mockup](https://user-images.githubusercontent.com/18539354/31311315-d9212754-aba9-11e7-8792-b3c53b525174.png)

**Comment by gchaincl** [comment]
:+1:

**Comment by stevenanthonyrevo** [comment]
Uploaded logo choices below will PR svg formats. 
A.
![httplab-vector-01](https://user-images.githubusercontent.com/8505293/31311524-e3b99d28-ab7b-11e7-8cf3-f13b0b7d19a1.png)
B.
![httplab-vector-02](https://user-images.githubusercontent.com/8505293/31311525-e3cfe628-ab7b-11e7-82ad-7acd759fbdbe.png)
Happy hacking this Hacktoberfest!

**Comment by gchaincl** [comment]
wow, looks very cool!

**Comment by esimov** [comment]
@vkolova i like it. However i would decrease the font size, i would move the text to the icon baseline and would change the light blue into a more solid blue.

**Comment by gchaincl** [comment]
I've created a poll so you can vote on the logo: https://github.com/gchaincl/httplab/issues/64

**Comment by gchaincl** [comment]
Closed by #65
