### ISSUE TITLE
Buffer Request Pane

### ISSUE THREAD

**Issue by SikhNerd** [gchaincl/httplab#6]
Would be nice to be able to scroll through previous requests, or support having multiple requests on-screen at once.

Useful when debugging something that sends multiple different payloads - can just point them all at httplab and understand the flow.

**Comment by gchaincl** [comment]
having an scroll seems great, but not sure about the UI, having multiple requests on-screen at once may be overkill, I'm thinking on a popup which displays them.

What do you mean with multiple different payloads?

**Comment by SikhNerd** [comment]
For example an android library that sends 5-6 different http calls. I want to send them all to httplab and inspect them.

**Comment by gchaincl** [comment]
how would you correlate them? by souece host perhaps? or you dont need to

**Comment by SikhNerd** [comment]
Don't particularly need to, because I'd review everything that was in httplab, or I'd only be sending the things I cared about, so I'd just page through all of them.

**Comment by gchaincl** [comment]
@SikhNerd mind to take a look at request-scroll [branch](https://github.com/gchaincl/httplab/tree/request-scroll), <kbd>PgUp</kbd> and <kbd>PgDown</kbd> will go back in time to inspect previous request

**Comment by SikhNerd** [comment]
@gchaincl Tested and works as advertised, I really like how it behaves when I've scrolled to a particular request and new requests are still coming in 👍

**Comment by gchaincl** [comment]
Cool!, I'll merge it
