### ISSUE TITLE
Graceful shutdown

### ISSUE THREAD

**Issue by gchaincl** [gchaincl/httplab#66]
Would be nice to enable graceful shutdown. Meaning that if there's an active connection at the moment the user sends a kill signal (Ctrl + C) HTTPLab will wait until all the connection has been closed.
Once signal has been sent, a message should be displayed with a message like: "HTTPLab is shutting down".

**Comment by maciekmm** [comment]
@gchaincl I can work on this. I have a question tho: if signal is resent in the 'waiting' state, shall we terminate httplab immediately?

**Comment by gchaincl** [comment]
Yeah that would be perfect
